### PR TITLE
Fix unwanted scopes collection modification in AzureIdentityAccessTokenProvider

### LINKED ISSUE #93: AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync
Method `AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync` will add the current uri to the instance variable `_scopes`. This is not thread-safe and might cause InvalidOperationExceptions because of collections that are modified concurrently. It also uses the current method parameter `uri`  to initialize the instance variable. Next time, when a different uri is used, scopes might be wrong.

My exception:

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at bool System.Collections.Generic.HashSet.AddIfNotPresent(T value, out int location)
at async Task Microsoft.Kiota.Authentication.Azure.AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(Uri uri, Dictionary additionalAuthenticationContext, CancellationToken cancellationToken)
at async Task Microsoft.Kiota.Abstractions.Authentication.BaseBearerTokenAuthenticationProvider.AuthenticateRequestAsync(RequestInformation request, Dictionary additionalAuthenticationContext, CancellationToken cancellationToken)
at async Task Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, string claims)
at async Task Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync(RequestInformation requestInfo, ParsableFactory factory, Dictionary> errorMapping, CancellationToken cancellationToken)
at async Task Microsoft.Graph.Users.UsersRequestBuilder.GetAsync(Action requestConfiguration, CancellationToken cancellationToken)
[...]
```

Current implementation:

```
        if(!_scopes.Any())
            _scopes.Add($"{uri.Scheme}://{uri.Host}/.default");
        span?.SetTag("com.microsoft.kiota.authentication.scopes", string.Join(",", _scopes));
        var result = await this._credential.GetTokenAsync(new TokenRequestContext(_scopes.ToArray(), claims: decodedClaim), cancellationToken);
``` 

Idea to fix this is to not modify `_scopes` instance variable but use a local array:

```
        string[] scopes = _scopes.ToArray();
        if (scopes.Length == 0)
            sopes = new string[] { $"{uri.Scheme}://{uri.Host}/.default" };
        span?.SetTag("com.microsoft.kiota.authentication.scopes", string.Join(",", scopes));
        var result = await this._credential.GetTokenAsync(new TokenRequestContext(scopes, claims: decodedClaim), cancellationToken);
```

### PR DESCRIPTION
**Pull request by schuettecarsten**
Also add missing .ConfigureAwait(false)
Fixes #93

### CODE REVIEW

**Comment by schuettecarsten** [comment]
I've also added a .ConfigureAwait(false) call and replaced the true/false values in SetTag method calls with pre-initialized, boxed values to prevent boxing and reduce heap usage.

**Review by baywet — CHANGES_REQUESTED** [review]
Thank you for the contribution.

Can you update the changelog and the csproj introducing a patch version and using tomorrow 's date please?

**Review by baywet — APPROVED** [review]
Thanks for making the changes. @andrueastman for final review and merge

**Review by andrueastman — APPROVED** [review]
Thanks for this @schuettecarsten

**Pull request merged**
